### ISSUE TITLE
Use with multiple locations

### ISSUE THREAD

**Issue by miscreantt** [claranet/rubrik-exporter#4]
Is there a way to use this to create dashboards with multiple Rubrik instances? Tried creating separate prometheus jobs pointing to separate docker instances on different ports and the stats are combined rather than having separate stats

**Comment by Gelob** [comment]
@miscreantt I don't run docker but the same concept applies. If you run two instances of the exporter on different ports you can use the below config in your prometheus.yml so that your instance name is not localhost or whatever IP your rubrik-exporter process runs on. Then when you import the dashboard from Grafana.net just change the queries to specify the instance. Such as `count(rubrik_vm_protected{instance="$device"} == 0)` for Total # of VMs not protected. You can change $device to be specifically your instance name as per the prometheus config. If you want to use the grafana template then make a variable named device with a query of `label_values(rubrik_system_storage_used , instance)`

I uploaded a templated dashboard based off the original here that has all of the queries changed already. https://grafana.com/dashboards/10272

I also made a systemd unit file I'll be sharing soon too.

```
  - job_name: 'rubrik site1'
    scrape_interval: 120s
    scrape_timeout: 30s
    static_configs:
    - targets: ['localhost:9477']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'myrubrik-site1.mydomain.com'

  - job_name: 'rubrik site2'
    scrape_interval: 120s
    scrape_timeout: 30s
    static_configs:
    - targets: ['localhost:9478']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'myrubrik-site2.mydomain.com'
```
